export const SET_VACANCY_STATUS = 'SET_VACANCY_STATUS'
export const SET_VACANCIES = 'SET_VACANCIES'
export const CREATE_VACANCY = 'CREATE_VACANCY'

export const SET_PERSON_STATUS = 'SET_PERSON_STATUS'
export const SET_PEOPLE = 'SET_PEOPLE'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const USER_CREATE = 'USER_CREATE'
export const USER_LOGIN = 'USER_LOGIN'
export const COMPANY_CREATE = 'COMPANY_CREATE'
export const COMPANY_LOGIN = 'COMPANY_LOGIN'

export const GET_COMPANY_PROFILE = 'GET_COMPANY_PROFILE'
export const GET_COMPANY_APPLICATIONS = 'GET_COMPANY_APPLICATIONS'

export const USER = 'user'
export const COMPANY = 'company'

export const GET_STATUS = 'GET_STATUS'
export const RESEND_VERIFICATION = 'RESEND_VERIFICATION'