export const APPLICATIONS = 'applications/'

export const GET_APPLICATIONS = 'GET_APPLICATIONS'
export const SET_APPLICATION = 'SET_APPLICATION'
export const MERGE_APPLICATIONS = 'MERGE_APPLICATIONS'

export const APPLY_VACANCY = 'APPLY_VACANCY'
export const ACCEPT_VACANCY = 'ACCEPT_VACANCY'
export const REJECT_VACANCY = 'REJECT_VACANCY'
export const DISCARD_VACANCY = 'DISCARD_VACANCY'
export const APPLY_STUDENT_VACANCY = 'APPLY_STUDENT_VACANCY'
export const ACCEPT_STUDENT_VACANCY = 'ACCEPT_STUDENT_VACANCY'
export const REJECT_STUDENT_VACANCY = 'REJECT_STUDENT_VACANCY'
export const DISCARD_STUDENT_VACANCY = 'DISCARD_STUDENT_VACANCY'

export const APPLICATIONS_REQUEST =  'APPLICATIONS_REQUEST'
export const APPLICATIONS_SUCCESS =  'APPLICATIONS_SUCCESS'
export const APPLICATIONS_ERROR   =  'APPLICATIONS_ERROR'
export const APPLICATIONS_CLEAN   =  'APPLICATIONS_CLEAN'