export const COMPANIES = 'COMPANIES'
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES'
export const GET_COMPANY = 'GET_COMPANY'

export const SET_COMPANY = 'SET_COMPANY'
export const SET_COMPANIES = 'SET_COMPANIES'

export const COMPANY_REQUEST = 'COMPANY_REQUEST'
export const COMPANY_SUCCESS = 'COMPANY_SUCCESS'
export const COMPANY_ERROR = 'COMPANY_ERROR'
export const COMPANY_CLEAN = 'COMPANY_CLEAN'