export const STUDENTS = 'students/'

export const STUDENT_REQUEST = 'STUDENT_REQUEST'
export const STUDENT_SUCCESS = 'STUDENT_SUCCESS'
export const STUDENT_ERROR = 'STUDENT_ERROR'
export const STUDENT_CLEAN = 'STUDENT_CLEAN'

export const GET_OWN_STUDENTS = 'GET_OWN_STUDENTS'
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS'
export const MERGE_STUDENTS = 'MERGE_STUDENTS'
export const MERGE_STUDENT = 'MERGE_STUDENT'
export const GET_STUDENT = 'GET_STUDENT'

export const APPLY_STUDENT = 'APPLY_STUDENT'

export const GET_STUDENT_STATUS = 'GET_STUDENT_STATUS'
export const GET_INCOME_STUDENTS = 'GET_INCOME_STUDENTS'
export const GET_OUTCOME_STUDENTS = 'GET_OUTCOME_STUDENTS'
export const GET_ACCEPTED_STUDENTS = 'GET_ACCEPTED_STUDENTS'
export const GET_REJECTED_STUDENTS = 'GET_REJECTED_STUDENTS'
