export const SURVEYS = 'surveys/'

export const SURVEYS_REQUEST = 'SURVEYS_REQUEST'
export const SURVEYS_SUCCESS = 'SURVEYS_SUCCESS'
export const SURVEYS_ERROR = 'SURVEYS_ERROR'
export const SURVEYS_CLEAN = 'SURVEYS_CLEAN'

export const GET_ALL_SURVEYS = 'GET_ALL_SURVEYS'
export const GET_SET_SURVEYS = 'GET_SET_SURVEYS'

export const MERGE_SURVEYS = 'MERGE_SURVEYS'

export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS'
export const GET_SET_QUESTIONS = 'GET_SET_QUESTIONS'