export const VACANCIES = 'vacancies/'

export const VACANCY_REQUEST = 'VACANCY_REQUEST'
export const VACANCY_SUCCESS = 'VACANCY_SUCCESS'
export const VACANCY_ERROR = 'VACANCY_ERROR'
export const VACANCY_CLEAN = 'VACANCY_CLEAN'

export const GET_OWN_VACANCIES = 'GET_OWN_VACANCIES'
export const GET_ALL_VACANCIES = 'GET_ALL_VACANCIES'
export const MERGE_VACANCIES = 'MERGE_VACANCIES'
export const MERGE_VACANCY = 'MERGE_VACANCY'
export const GET_VACANCY = 'GET_VACANCY'

export const GET_VACANCY_STATUS = 'GET_VACANCY_STATUS'
export const GET_INCOME_VACANCIES = 'GET_INCOME_VACANCIES'
export const GET_OUTCOME_VACANCIES = 'GET_OUTCOME_VACANCIES'
export const GET_ACCEPTED_VACANCIES = 'GET_ACCEPTED_VACANCIES'
export const GET_REJECTED_VACANCIES = 'GET_REJECTED_VACANCIES'

export const GET_INCOME_CVS = 'GET_INCOME_CVS'
export const GET_OUTCOME_CVS = 'GET_OUTCOME_CVS'
export const GET_ACCEPTED_CVS = 'GET_ACCEPTED_CVS'
export const GET_REJECTED_CVS = 'GET_REJECTED_CVS'
