export const VACANCIES = 'vacancies/'
export const GET_OWN_VACANCIES = 'GET_OWN_VACANCIES'
export const GET_ALL_VACANCIES = 'GET_ALL_VACANCIES'
export const MERGE_VACANCIES = 'MERGE_VACANCIES'
export const GET_VACANCY = 'GET_VACANCY'
